language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bellockk
  password:
    secure: Qnz3zpVsWQAhiLVO7Cw6zzP2lubyO7MCBMFdJxGVSI4YP44YuUpKa3ZkXp0Ju91IJJ1T5MTB4DalBk+O4HOxpB6GPraFvb4pkGdlUesLxP6Co+jiR/PDFetqcXyorz70gCbC4jJM+wgiqCxQyXuXZfgPN72i2bkKfgW2szYvFr/0FuMYbgwK7BGus+33H0d9bt/MhtDia8wFheKgUYsrAwjVPB5sjlClGos6Lk7go4XUKme96mv1ob49hrYlpgVcfxjv51EXn75jeu0xbNsmCBqM9QYqC6k7KvIsv7AWUovne7SA7m5pwusDrTVekQnD9BIXaTBvBQGqTlC8ieF7nq9hSOox803GDon5rfuncpgmuQHoxv5aJkf0AZb7OMC3tN7kY1YpgzFoovX/uXyOt9CpSrCcPuawOFTlHygA5ct1WaAUBG3pkOVVv+0kR2F/TJRSRV9HAI1URqcSqhBRs5rZfomqzjHS80r1M+968vEWGScbwMb2R9Cgj9+PyH89wFzM7eb8IMxRT4DBMOQegkD/fFHhiRxDFigm1asSc/ubjw+I4trJVv1S3DbSh4rlvaZrG88FBEbBq7gpadcC8zjRCdeZEtIxfQXaZeDE/yoRN317CPe64WzTJxQKR/bBSnRXAVh6QRukpm4YNptNJxzS7wocl5W803/5CLPT0I0=
  on:
    tags: true
    repo: bellockk/amtool
    python: 3.6
