language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bellockk
  password:
    secure: RFJqQfApatdOkjPkoxsVXLBbo0KvbR7k1UK8+BGURdSZ9cqSbsWdrJDVObdr4xWRhWEOcG9vH9oHD5592G9Rl/jExKB9bWhwZCsUd3G0vuJjWJufrQGtgaYcMsF+7K6VGoFo6KOukV4kKErhrypb/CzyQRaVOFyKqw5c8EWdzi7h0ByiSNdYw0p9dAI7DGjaeEhAR8gbOOhhCTXZplZslYaObbI5VJYaz9oBYr4k1zYoHW7kO1dFZk0KvYEByV6V/hS8ykWA4XnMRAOHlUQ34iDahbdXrOSXsrbqVJaE44VhZbu9ncFAxWtOwTzeLNVue3iSfnBZAgS5P0uNDaTNRLv9BmEiJLYZnBc8YvLHoWj7ybm2qCz4n+vm9Rrjf8LFyYoNXu/sNrpi/RC7rBA/36u5wqTeSDZRNyKRxCcvHEajQp3cDwLz8YpbaG1+oR1JmdriadsPp1zVVQV42MLJ6pcpTppg2RlpXpSI1BVinfLaia7h7jzFAi3mU0F4VRF4YWxHu4suUdvlx4obTTjmALdUlmzl0h5PvnEgKRrgrFDCDCfouhvwuMy/aTdws43NPjJT84aJJnYAmH5lZKacEFMd6pXnVxQQc5i0K7jqRBpdiEFAaHqsyQYT2QLZMWSwdEyJe13Q1rV7mOjDcz2qtDBzC48yvPCw9M2DOj5eg94=
  on:
    tags: true
    repo: bellockk/amtool
    python: 3.6
